name: Execution Performance

on:
  workflow_dispatch:
    inputs:
      testSuite:
        type: string
        description: 'Test Suite to execute'
        required: true
        default: 'pokemonapi.PokemonTestApi'
      quantityUsers:
        type: string
        description: 'Quantity of users concurrent'
        required: true
        default: '5'

jobs:
  execpokemonapi:
    runs-on: ubuntu-latest
    name: Execution Performance Pokemon API
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3

      - name: Execute test
        run: gradle gatlingRun --simulation=${{ inputs.testSuite }} -DquantityUsers=${{ inputs.quantityUsers }}

      - name: Save report
        if: ${{always()}}
        uses: actions/upload-artifact@v3.1.2
        with:
          name: gatling report
          path: ./build/reports/gatling

      - name: Determinate result folder
        id: result_folder
        run: ls ./build/reports/gatling | head -1

      - name: Publish test results
        uses: peaceiris/actions-gh-pages@v3.7.3
        if: ${{ always() }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: './build/reports/gatling/${{ steps.result_folder.outputs }}'
          keep_files: true
          user_name: refloresmaynasa
          user_email: ricky.reflores@gmail.com
          publish_branch: gh_page
